module.exports = {
  purge: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        primary: "#3964ae",
        secondary: "#8c96a3",
        ternary: "#0e5cad",
        success: "#0bd08e",
        warning: "#ebac2f",
        error: "rgb(245, 72, 72)",
        dark: "#343944",
        link: "#343944",
        font: "#343944",
        grey: "#bbb",
        disabled: "#F8F8F8",
        greyFont: "#9c9c9c",
        middleGrey: "#8c96a3",
        lightGrey: "#c5ccd6",
        modal: "#343944",
        highlight: "yellow",
        info: "#3964ae",
        radio: "#0bd08e",
        green: "#0bd08e",
        blue: "#0e5cad",
        offBlue: "#3964ae",
        darkBlue: "#0f358e",
        red: "rgba(245, 72, 72, 0.95)",
        orange: "#ebac2f",
        pink: "rgba(230, 121, 125, 0.15)",
        arrow: "inherit",
        dropdownArrow: "white",
        placeholder: "inherit",
        border: {
          dark: "#343944",
          default: "#e8e8e8",
          light: "#e8e8e8",
        },
        background: {
          loader: "rgba(0, 0, 0, 0.3)",
          sideMenu: "rgba(0, 0, 0, 0.5)",
          modal: "rgba(0, 0, 0, 0.8)",
          sideMenuContent: "#fff",
          modalContent: "#fff",
          grey: "#f8f8f9",
          lightGrey: "#f8f8f9",
          chat: {
            input: "rgba(187, 187, 187, 0.2)",
            file: "rgba(187, 187, 187, 0.4)",
          },
        },
      },
      borderWidth: {
        form: "1px",
      },
      borderRadius: {
        default: "4px",
        button: "4px",
        scrollBar: "4px",
      },
      fontSize: {
        default: "14px",
        label: "10px",
        message: "12px",
        form: {
          small: "13px",
        },
      },
      boxShadow: {
        field: {
          switch: "1px 0px 8px 0 rgba(0,0,48,.18)",
          active: "0 0 10px 0 rgba(0, 0, 0, 0.05)",
        },
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
